# Generated by Django 4.2 on 2023-08-18 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='class_name',
            new_name='clas_name',
        ),
    ]
