# Generated by Django 4.2 on 2023-08-18 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_rename_class_name_section_clas_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='year',
            old_name='year',
            new_name='year_name',
        ),
    ]
