# Generated by Django 4.2 on 2023-08-18 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_rename_year_year_year_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='clas_name',
        ),
        migrations.AddField(
            model_name='section',
            name='clas_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.class'),
        ),
    ]
