# Generated by Django 4.2.4 on 2023-09-08 04:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=100)),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('teacher', models.CharField(max_length=100)),
                ('clas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.class')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.section')),
                ('sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.subject')),
            ],
        ),
    ]
