# Generated by Django 4.2 on 2023-09-08 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routine',
            name='sub',
            field=models.TextField(blank=True),
        ),
    ]
