# Generated by Django 4.2 on 2023-09-13 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_principle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('image', models.FileField(upload_to='students')),
                ('fname', models.CharField(max_length=100)),
                ('mname', models.CharField(max_length=100)),
                ('roll', models.CharField(max_length=10000)),
                ('due_date', models.DateField()),
                ('blood', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=20)),
                ('clas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.class')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.section')),
            ],
        ),
    ]
