# Generated by Django 4.2 on 2023-09-13 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_student'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Students',
        ),
    ]
