# Generated by Django 4.2 on 2023-09-13 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_rename_student_students'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='clas',
            new_name='cs',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='section',
            new_name='sex',
        ),
        migrations.AlterField(
            model_name='students',
            name='image',
            field=models.FileField(upload_to='stu'),
        ),
    ]
