# Generated by Django 4.2 on 2023-09-13 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_rename_clas_students_cs_rename_section_students_sex_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='cs',
            new_name='clas',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='sex',
            new_name='section',
        ),
    ]
