# Generated by Django 4.2 on 2023-09-13 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_rename_cs_students_clas_rename_sex_students_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='clas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.class'),
        ),
        migrations.AlterField(
            model_name='students',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.section'),
        ),
    ]
