# Generated by Django 4.2 on 2023-09-13 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_alter_students_clas_alter_students_section'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='section',
            new_name='sec',
        ),
    ]
