# Generated by Django 4.2.4 on 2023-09-15 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_sovapoti'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='join',
            field=models.DateField(blank=True, null=True),
        ),
    ]
